[project]
name = "DecodeTheBot"
version = "0.1.0"
description = "Decoding The Guru Podcast companion"
authors = [
    { name = "pawrequest", email = "paw@pawrequest.com" }
]
dependencies = [
    'sqlmodel',
    "uvicorn",
    'fastapi',
    'pydantic',
    'python-dotenv',
    "aiohttp",
    "loguru",
    "fastui",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = false
dev-dependencies = [
    "pytest",
    "pytest-asyncio",
    "httpx",
]

[tool.ruff]
line-length = 100

[tool.hatch.metadata]
allow-direct-references = true

